---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ac-svc
  namespace: default
  labels:
    name: k8s-ac
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: k8s-ac