---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-ac
webhooks:
  - name: k8s.ac.valid
    clientConfig:
      service:
        name: k8s-ac-svc
        namespace: default
        path: "/mutate"
      caBundle: "${CA_BUNDLE}"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["apps",""]
        apiVersions: ["v1"]
        resources: ["pods","deployments"]
    failurePolicy: Ignore